[package]
name = "tapt-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
derive_more = { workspace = true }
tapt-parser = { path = "../parser" }
tapt-vm = { path = "../vm" }

[lints]
workspace = true
